#!/bin/bash

# anshul333y's hyprstyle script

WALLDIR="$HOME/pics/wall"
SYMLINK="$HOME/pics/wall.jpg"

if [[ -n "$1" ]]; then
  WALLPAPER="$1"
  ln -sf "$WALLPAPER" "$SYMLINK"
else
  mapfile -t files < <(find "$WALLDIR" -type f -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" | sort)
  [[ -L "$SYMLINK" ]] || ln -sf "${files[0]}" "$SYMLINK"
  for i in "${!files[@]}"; do [[ "${files[$i]}" == "$(readlink "$SYMLINK")" ]] && idx=$i; done
  WALLPAPER="${files[$(((idx + 1) % ${#files[@]}))]}"
  ln -sf "$WALLPAPER" "$SYMLINK"
fi

source ~/.python-venv/bin/activate 2>/dev/null
TERM=dumb wal -i "$WALLPAPER" 2>/dev/null

gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER"
if pgrep -x "Hyprland" >/dev/null; then
  pkill waybar
  pkill hyprpaper
  hyprpaper &>/dev/null &
  waybar &>/dev/null &
  hyprctl reload
fi
