#!/usr/bin/env bash

# anshul333y's update script

separator() {
  printf "\n%${COLUMNS}s\n\n" | tr ' ' '-'
}

if command -v apt >/dev/null 2>&1; then
  sudo apt update
  separator
  sudo apt upgrade -y
  separator
  sudo apt autoremove -y
fi

if command -v pacman >/dev/null 2>&1; then
  sudo pacman -Syu --noconfirm
  separator
  sudo pacman -Rsu --noconfirm $(pacman -Qdtq)
  separator
  paru -Syu --noconfirm
fi

if command -v nixos-rebuild >/dev/null 2>&1; then
  separator
  sudo nix flake update /etc/nixos
  sudo nixos-rebuild switch --flake /etc/nixos
fi

if command -v flatpak >/dev/null 2>&1; then
  separator
  flatpak update -y
  separator
  flatpak uninstall -y --unused
fi
